services:
  sql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "${DEV_DB_PASSWORD}"
    ports:
      - "1433:1433"
    volumes:
      - devflow-sql-data:/var/opt/mssql

  azurite:
    image: mcr.microsoft.com/azure-storage/azurite
    ports:
      - "10000:10000" # blob endpoint

  mailhog:
    image: mailhog/mailhog
    ports:
      - "1025:1025" # SMTP
      - "8025:8025" # web UI

volumes:
  devflow-sql-data:
